/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const RoadmapModel = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/roadmap.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={[0.5, 0.5, 0.5]}
      position={[0, 0, 0]}
    >
      <group name="Scene">
        <mesh
          name="GLB-Top"
          castShadow
          receiveShadow
          geometry={nodes['GLB-Top'].geometry}
          material={materials['Basic CD Case']}
        >
          <mesh
            name="Curve004"
            castShadow
            receiveShadow
            geometry={nodes.Curve004.geometry}
            material={materials.HoloStickerGLB}
            position={[-4.94, -4.66, 0.29]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={11.53}
          />
          <mesh
            name="Text002"
            castShadow
            receiveShadow
            geometry={nodes.Text002.geometry}
            material={materials.HoloStickerGLB}
            position={[4.27, 4.16, 0.19]}
            rotation={[0, -1.57, 0]}
          />
        </mesh>
        <group name="GLB-Bottom">
          <mesh
            name="Cube042"
            castShadow
            receiveShadow
            geometry={nodes.Cube042.geometry}
            material={materials['Basic CD Case']}
          />
          <mesh
            name="Cube042_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube042_1.geometry}
            material={materials['Basic Case Back']}
          />
          <mesh
            name="Cube042_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube042_2.geometry}
            material={materials['Basic CD Case']}
          />
        </group>
        <group name="GLB-Disk">
          <mesh
            name="Cube041"
            castShadow
            receiveShadow
            geometry={nodes.Cube041.geometry}
            material={materials['LILY-CD']}
          />
          <mesh
            name="Cube041_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube041_1.geometry}
            material={materials['Material.003']}
          />
          <mesh
            name="Cube041_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube041_2.geometry}
            material={materials['CD Black']}
          />
        </group>
        <mesh
          name="GLB-Clip"
          castShadow
          receiveShadow
          geometry={nodes['GLB-Clip'].geometry}
          material={materials['Rainbow Clip.001']}
        />
      </group>
    </group>
  )
}

export default RoadmapModel

useGLTF.preload('/models/roadmap.gltf')
