/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const RoadmapModel = (props: any) => {
  const { nodes, materials } = useGLTF('/models/Lily-Lotus-3D.gltf')

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube041.geometry}
        material={materials['CD-Raw']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube041_1.geometry}
        material={materials['CD Black']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube042.geometry}
        material={materials['Basic CD Case']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube042_1.geometry}
        material={materials['Basic CD Case']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GLB-Top'].geometry}
        material={materials['Basic CD Case']}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve004.geometry}
          material={materials.HoloStickerGLB}
          position={[-4.94, -4.66, 0.29]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={11.53}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text002.geometry}
          material={materials.HoloStickerGLB}
          position={[4.27, 4.16, 0.19]}
          rotation={[0, -1.57, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GLB-CD-Sticker'].geometry}
        material={materials['CD-Sticker']}
        position={[0, 0, 0.04]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={4.73}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GLB-CD-Sticker001'].geometry}
        material={materials['CD-Sticker']}
        position={[0, 0, 0.04]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={4.22}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GLB-Clip'].geometry}
        material={materials['Rainbow Clip.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GLB-Backpaper'].geometry}
        material={materials['Basic Case Back']}
        position={[0, 0, -0.18]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[5.23, 4.98, 4.98]}
      />
    </group>
  )
}

useGLTF.preload('/models/Lily-Lotus-3D.gltf')

export default RoadmapModel
